name: ci
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - run: make install
      - run: make lint

	sonarqube:
		runs-on: ubuntu-latest
		needs: check  # Зависит от успешного выполнения job 'check'
		steps:
		  - uses: actions/checkout@v4
		  - uses: actions/setup-node@v4
			with:
			  node-version: '20'
			  cache: 'npm'
		  - run: make install
		  - name: Run SonarQube Scan
			uses: SonarSource/sonarqube-scan-action@master
			env:
			  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
			  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}